### ISSUE TITLE
Walker Nav

### ISSUE THREAD

**Issue by ambadesign** [babobski/Bootstrap-on-WordPress#22]
**Description (small description where the bug is about):**  
When you add a parent page and child pages to the menu, not only is the parent not clickable, but the children don't drop down either.

**Expected result:**  
Parent and child menu items should be clickable and dropdown respectively.

**Actual result:**  
Parent not clickable. Child menu does not drop down.

**Steps to reproduce**  
Added parent menu item with children.

**Comment by babobski** [comment]
I changed the bootstrap nav walker when making it bootstrap 5 ready. 
Can you test if you switch it back to the bootstrap 4 nav walker, it's fixes the issue?

The bootstrap 4 nav walker is still present in the theme.
You have to change the include back to `bs4navwalker.php` on line:
https://github.com/babobski/Bootstrap-on-WordPress/blob/master/functions.php#L33

You can then use the old navwalker like:

https://github.com/babobski/Bootstrap-on-WordPress/blob/2d2ce9c02a42294340396d3a05b4c477fa408121/parts/shared/header.php

**Comment by babobski** [comment]
Thanks for the report, fixed it in the latest release

**Comment by ambadesign** [comment]
Thank you for the fix; however there is another issue. The mobile menu does not work at all - can you fix this as well please?

**Comment by babobski** [comment]
Thanks for the report! fixed it in the latest release.

**Comment by ambadesign** [comment]
I've downloaded the latest release and the mobile menu doesn't trigger at all. I've tested this on a site we were building for a client and on a new, bare bones install and it's still not working. You click on the hamburger and nothing happens.

**Comment by babobski** [comment]
The button was not working because the data-attributes has changed from data- to data-bs-. I've changed this in the `parts/shared/header.php ` to make it work again with Bootstrap 5. Can you check the file in you're template if you see these [changes](https://github.com/babobski/Bootstrap-on-WordPress/commit/f07709dc5f38f9ee73c0a34b4d192f7df0f048f8)?

**Comment by ambadesign** [comment]
Ooooh I see! No it wasn't changed, but I've now changed it and wah lah! All kicks in! Thanks for that, appreciate it.
