### ISSUE TITLE
Boostrap 1.5 icons

### ISSUE THREAD

**Issue by bradgillap** [babobski/Bootstrap-on-WordPress#28]
Hi thanks,

Just wanted to say this is really nice and well thought through. Even better than some of the wordpress built in themes.

Wonder if you considered adding the bootstrap icons as well to this.  Something like this based on the 1.5 binary works good in the functions.php

```
wp_register_style( 'bootstrap-icons', get_template_directory_uri() . '/icons/font/bootstrap-icons.css', array(), '1.5', 'all' );
wp_enqueue_style( 'bootstrap-icons' );
```

**Comment by babobski** [comment]
Thanks for the request! 
I've added the icon font in the latest release.
