### ISSUE TITLE
Add site logo / offcanvas right

### ISSUE THREAD

**Issue by micreativespace** [babobski/Bootstrap-on-WordPress#37]
Hello,

I love the theme update to 5.2.2 thank you.

Please can you add site logo option and offcanvas option to the right?

**Comment by babobski** [comment]
Hi Morning, what are you trying to achieve?
If you want to move the default menu to the other side, you can change the [offcanvas class](https://github.com/babobski/Bootstrap-on-WordPress/blob/master/parts/shared/header.php#L7) from `offcanvas-start` to `offcanvas-end` then it will open from the right side. 
Or do you want to add a second offcanvas menu from that opens from the other side?

If you want to use a logo or logo with text, you can follow the [bootstrap documentation](https://getbootstrap.com/docs/5.2/components/navbar/#image) for replacing the [default text](https://github.com/babobski/Bootstrap-on-WordPress/blob/master/parts/shared/header.php#L14) with a logo.

If you want to use a logo with text, personally I would take a other approach tan the docs would recommend.
I would use flexbox to align the image and text horizontal like this:

```html
<nav class="navbar bg-light">
  <div class="container-fluid">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <img src="https://getbootstrap.com/docs/5.2/assets/brand/bootstrap-logo.svg" alt="Logo" class="me-2" width="30" height="24">
      Bootstrap
    </a>
  </div>
</nav>
```

**Comment by micreativespace** [comment]
Thank you for the info. I will add an svg in place of the text for branding.

**Comment by babobski** [comment]
That's oke, then I will close the issue
