### ISSUE TITLE
page title 'content h2'

### ISSUE THREAD

**Issue by micreativespace** [babobski/Bootstrap-on-WordPress#38]
Hello,

How to remove the page title without plugin?

In the theme 'sample page' page title is 'conent h2' class but doing 'display:none' removes all h2 titles.

**Comment by babobski** [comment]
You can just remove it from the template, I don't know on which page page or post you want to remove it.
You can see in the documentation of the [template hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/) which file you can edit. If you want a separate template for you're homepage you can add home.php in the theme directory.

If you want to hide it for a specific page or post, you can use [conditional tags](https://codex.wordpress.org/Conditional_Tags) to do so.
