### ISSUE TITLE
Specific Plugin Conflict with theme - possible to help?

### ISSUE THREAD

**Issue by thinkDru** [babobski/Bootstrap-on-WordPress#7]
First of all, love the theme! Thanks for providing us with it my dude. 

I am using this latest version of your theme and running into a plugin conflict with Wordpress Search & Filter [Search & Filter](https://wordpress.org/plugins/search-filter/). 

Once activated and implemented, if you try to search for something or select an item from the dropdowns, nothing happens and the page reloads itself. 

I have changed themes to Wordpress TwnetySeventeen and it works as intended (adding search params in the URL) but when switching back to your theme, it doesn't work. I do not have any other plugins installed to cause conflicts so I am wondering if there is a theme conflict?.

Is it possible for you to try and re-produce this on your end? I appreciate any help you can provide.

Cheers

**Comment by babobski** [comment]
@thinkDru I looked into the issue, but I don't see what is causing the issue.
Tried some various things, but don't see what is causing it.

Looked at the demo sites, but the setup is quite different here.
Here the are using ajax to update the page.

You might want to check out this [issue](https://github.com/rmorse/search-filter/issues/6) I tried the debug bar, but it is not helping me.

Can you report back if this is a theme issue.
